### PR TITLE
📝 Fix minor inconsistencies and typos in tutorial

### PR DESCRIPTION
**Pull request by tvoirand**
I think I saw a couple of typos or inconsistencies in the tutorial:
- Grammar error in `commands/one-or-multiple.md`
- Wrong command listed in `command/options.md`
- What looks to be missing words in `first-steps.md` (I doubt a typer "parameter" or "argument" refers to a python function)

Thanks a lot for your work on this great tool. I hope this helps!

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
All three are a nice catc, thanks! Looks good to merge.

**Review by patrick91 — APPROVED** [review]

**Comment by tvoirand** [comment]
Thanks for your feedback.

Oops sorry, I realize I had not updated the python files associated with the code block impacted by my update in `commands/one-or-multiple.md`. I just corrected this with my second commit.

(I had not thoroughly read and applied the [contributing guide](https://typer.tiangolo.com/contributing/#docs-structure) that describes this link between docs and python files/tests. That should teach me!)

**Review by svlandeg — APPROVED** [review]
Right, good catch!

**Review by tiangolo — APPROVED** [review]
Great, thanks! :rocket: :mag:

**Pull request merged**
