### PR TITLE
✨ Update `launch` to not print anything when opening urls

### PR DESCRIPTION
**Pull request by patrick91**
It's not launch that does this, but the actual browsers that print text when starting, see:

image

This PR updates launch to handle URLs and swallow the output being printed by browsers (when possibile)

It now looks like this:

image

### CODE REVIEW

**Comment by patrick91** [comment]
Just double checked and click might have this already, I remember checking though 😅

**Comment by patrick91** [comment]
Actually, this might still be useful: 
CleanShot 2024-10-30 at 13 59 21@2x

**Comment by patrick91** [comment]
yup, this fixes the issue on ubuntu: 
CleanShot 2024-10-30 at 15 13 28@2x

**Review by tiangolo — APPROVED** [review]
Awesome, thank you @patrick91! :rocket: :cake:

**Comment by paketb0te** [comment]
@patrick91 just out of curiosity, which combination of python / OS / Browser did you find to be spammy?
You mention Chrome in the docstring of `launch()`, but at least on ubuntu I see no terminal output when using `webbrowser.open()` or `webbrowser.get().open()` (py3.8 to py3.13).
So I guess it is happening on macOS?

**Comment by patrick91** [comment]
@paketb0te yes, it was a fresh install of ubuntu, and I think it was Chromium 😊

**Pull request merged**
