### PR TITLE
🐛 Fix support for `UnionType` (e.g. `str | None`) with Python 3.11

### LINKED ISSUE #533: Using `some_type | None` syntax for type annotations causes error in python 3.11
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer
from datetime import datetime
print(typer.__version__)

app = typer.Typer()

@app.command()
def f(x: datetime | None = None):
    print(x)

if __name__ == "__main__":
    app()
```

### Description

In python 3.10 this script runs as expected, but on 3.11 I get the following error

```
Traceback (most recent call last):
  File "/Users/pcrein/qdash/test.py", line 16, in <module>
    app()
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 364, in get_command
    click_command = get_command_from_info(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 577, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 553, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 844, in get_click_param
    parameter_type = get_click_type(
                     ^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 773, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Type not yet supported: datetime.datetime | None
```

### Operating System

macOS

### Operating System Details

_No response_

### Typer Version

0.7.0

### Python Version

3.11.0

### Additional Context

I believe the issue is that for some reason, `typing.get_type_hints` is no longer converting the `UnionType` into a `Union`. I would suggest as a fix that `get_click_param` use `typing.get_origin/get_args` instead of `__args__` and `__origin__` attributes.

### PR DESCRIPTION
**Pull request by jonaslb**
Potential solution for #533, which already had good details and a proposal for a solution, based on using `get_args` and `get_origin` from the `typing` module instead of the `__args__` and `__origin__` attributes. So I went and did that.

We also needed to actually handle the `UnionType` in addition to the `Union` from before. 

Now there was a bit of a headache in terms of writing this in a backwards compatible way. What I've done is place the compatibility code into `_compat_utils.py`. But let me know if you'd prefer to keep it in `main.py`.

I also added a single test, just an adapted copy of another one with the `x | None` syntax. It is conditioned on Python >= 3.10, so it shouldn't fail on older Pythons.

### CODE REVIEW

**Comment by jonaslb** [comment]
It looks like mypy behaves differently in the different tests across versions. 3.6, 3.10 and 3.11 are ok, but 3.7, 3.8 and 3.9 are not. That seems confusing. I can maybe look at it another day again, otherwise if someone can see why it happens let me know.

**Comment by jonaslb** [comment]
Failures are down to mypy version I think, it works fine here with latest. I see some errors in other places though.

Also realized there is already another PR for this issue (just references other issue numbers, so I hadn't seen it): #522 

Regardless, hope to see either PR merged. Ping @tiangolo

**Comment by austin-silk** [comment]
@tiangolo - can we merge this please?

**Comment by jonaslb** [comment]
Rebased on master and now all is green 👍

Still happy to make adaptations or answer questions.

**Comment by jonaslb** [comment]
@svlandeg I gather that #676 is the preferred solution to the UnionType situation? Should I just close this? Will we ever get anything on the topic merged - ie. what's blocking?

**Comment by svlandeg** [comment]
Hi @jonaslb, we've been going through the backlog of PRs to label them and connect related ones. We've already reviewed, adapted and merged a bunch for last week's releases 0.9.1 through 0.11.0. Open-source maintenance costs time and effort as I hope you can appreciate ;-) Thanks for your contributions (and patience) so far, we'll definitely get to this!

**Comment by jonaslb** [comment]
> Open-source maintenance costs time and effort as I hope you can appreciate ;-)

Of course, and it's great to see that time is now being spent on typer also from the maintainer side ;-) I'm looking forward to engaging about details here if this PR turns out to be the preferred one out of the many submitted on the topic.

**Review by svlandeg — APPROVED** [review]
I confirmed that this behaviour works in 3.10 but broke in 3.11, and the unit test introduced in this PR captures the bug nicely.

I updated this PR so that the changes would be more minimal, using the variables from `_typing` that were introduced precisely for this type of usage.

This PR now closely resembles https://github.com/tiangolo/typer/pull/676, though this one captures a few additional cases where `__args__` and `__origin__` are called directly in the main code. I think it's a good idea to rewrite all of these cases.

As such, I recommend to merge this PR and close #676 (and #739), but I'll leave the final decision with Tiangolo.

**Comment by lachaib** [comment]
Ruff tries to automatically fix these `Optional[str]` in my parameters and I had to disable it, so I'm really looking forward to seeing this merged and released.

**Comment by luispsantos** [comment]
@tiangolo I understand you have other time commitments and it must be overwhelming, but I would like to have this PR merged when possible. I use Ruff with `pyupgrade` rules like @lachaib and I find lack of the modern union support a considerable hindrance when using Typer and Ruff together.

**Review by patrick91 — APPROVED** [review]

**Comment by tiangolo** [comment]
Great! Thank you for your contribution @jonaslb!  :cake: 

And in particular, thank you for your patience and your kindness. :hugs: 

Thank you @svlandeg for the great job as always investigating, reviewing, and reporting everything. :bow: 

This will be available in Typer `0.12.4`, released in the next hours. :tada:

**Comment by NikosAlexandris** [comment]
Does this "fix" not include support for `X | Y  | Z` ?

**Comment by jonaslb** [comment]
This was always a fix for `X | None` only, i.e. #533. It looks like an error that it was not closed yet (likely because I didn't use the magic words in the description..). #461 looks like the issue for what you seek.

**Pull request merged**
