### PR TITLE
🐛 Fix support for UnionType with Python 3.11

### LINKED ISSUE #533: Using `some_type | None` syntax for type annotations causes error in python 3.11
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import typer
from datetime import datetime
print(typer.__version__)

app = typer.Typer()

@app.command()
def f(x: datetime | None = None):
    print(x)

if __name__ == "__main__":
    app()
```

### Description

In python 3.10 this script runs as expected, but on 3.11 I get the following error

```
Traceback (most recent call last):
  File "/Users/pcrein/qdash/test.py", line 16, in <module>
    app()
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 364, in get_command
    click_command = get_command_from_info(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 577, in get_command_from_info
    ) = get_params_convertors_ctx_param_name_from_function(command_info.callback)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 553, in get_params_convertors_ctx_param_name_from_function
    click_param, convertor = get_click_param(param)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 844, in get_click_param
    parameter_type = get_click_type(
                     ^^^^^^^^^^^^^^^
  File "/Users/pcrein/.pyenv/versions/qdash-3.11.0/lib/python3.11/site-packages/typer/main.py", line 773, in get_click_type
    raise RuntimeError(f"Type not yet supported: {annotation}")  # pragma no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Type not yet supported: datetime.datetime | None
```

### Operating System

macOS

### Operating System Details

_No response_

### Typer Version

0.7.0

### Python Version

3.11.0

### Additional Context

I believe the issue is that for some reason, `typing.get_type_hints` is no longer converting the `UnionType` into a `Union`. I would suggest as a fix that `get_click_param` use `typing.get_origin/get_args` instead of `__args__` and `__origin__` attributes.

### PR DESCRIPTION
**Pull request by standag**
Resolves #533

### CODE REVIEW

**Comment by thomasaarholt** [comment]
This worked like a charm! Thank you!

**Comment by adam-moss** [comment]
This is a very nice addition 👍

**Comment by standag** [comment]
Sorry, I cannot, I haven't write access to this repository.

**Comment by coreegor** [comment]
@standag So you can't set @tiangolo as the assignee ?

**Comment by standag** [comment]
> Who can use this feature
> Anyone with write access to a repository can assign issues and pull requests.
https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Review by disrupted — APPROVED** [review]

**Comment by disrupted** [comment]
also resolves #348

**Comment by aronbierbaum** [comment]
Are there any updates on this pull request. Would love to not need to use `Optional` or `Union`.

**Comment by tino** [comment]
@disrupted is @tiangolo the only one that can merge? Seems a bit wasteful that this is sitting here with 2 approves and a passing CI just waiting.

**Comment by disrupted** [comment]
> @disrupted is @tiangolo the only one that can merge? Seems a bit wasteful that this is sitting here with 2 approves and a passing CI just waiting.

Looks like it. My review only has symbolic value as I am not a maintainer.

**Comment by svlandeg** [comment]
Related PR: https://github.com/tiangolo/typer/pull/548

**Comment by sebastian-correa** [comment]
Will this be merged anytime soon? @tiangolo 

This has become a sore point with Typer in our code.

**Review by svlandeg — APPROVED** [review]
I confirmed that this behaviour works in 3.10 but broke in 3.11, and the unit test introduced in this PR captures the bug nicely.

The fix is very clean and minimal, using the variables from `_typing` that were introduced precisely for this type of usage.

Thanks for the contribution @standag!

**Comment by svlandeg** [comment]
Update: https://github.com/tiangolo/typer/pull/548 contains all the changes that are also in this PR, as well as a few additional rewrites. As such, I recommend to merge #548 and close this one, but I'll leave the final decision with Tiangolo.

**Review by ml31415 — APPROVED** [review]
Looks good. Please merge.

**Comment by ml31415** [comment]
Dear Sebastian @tiangolo ,
please consider adding one or two trusted persons as maintainers for this package. Python 3.13 is about to come out and this issue for py3.11 is still not fixed, despite long time opened pull requests. I have full understanding for being busy or losing interest in maintenance for a package after a while. But the community is here to help out, to keep this package going. Please just let the community do it's job!

**Comment by tiangolo** [comment]
Thank you for the work @standag! :coffee: 

And thanks @svlandeg for all the help :bow: 

This should have been fixed by https://github.com/fastapi/typer/pull/548

It is now available in Typer `0.12.4` :rocket: 

Given that, I'll close this one.

**Pull request closed without merging**
