### PR TITLE
🐛 Fix `no_args_is_help` for 0 and 1 command Typer Apps

### PR DESCRIPTION
**Pull request by JacobBush**
Resolves https://github.com/tiangolo/typer/issues/450

### CODE REVIEW

**Comment by Migi** [comment]
For what it's worth, I've reviewed this PR and it looks good to me. But I'm not a maintainer of this project, just someone who encountered this same bug.

**Comment by svlandeg** [comment]
Good catch - it does look like this is a bug we should resolve. We'll look into this.

[maintenance note] As this feature didn't have any documentation examples or tests, I suggest to review/merge https://github.com/tiangolo/typer/pull/751 first.

**Review by svlandeg — COMMENTED** [review]
Thanks again for this contribution! 

I reviewed the cases outlined in #450 and confirmed that they break on `master` and are fixed with this PR. Further, the unit test you've added here seems to accurately cover these cases. So in terms of behaviour/functionality this PR looks good. 

Thee only thing I'm unsure about is whether we want/need to fix this in the `get_command` function, and whether there might not be unexpected side effects from this fix. I'll leave the final review for Tiangolo.

**Comment by jonboulle** [comment]
Any chance of revisiting this? :eyes:

**Comment by tiangolo** [comment]
Thanks @JacobBush! I would consider things to be running as expected.

In short, the main case with a single sub-command would be:

```Python
import typer

cli = typer.Typer(no_args_is_help=True)


@cli.command("1")
def _1():
    print(1)


@cli.callback()
def callback():
    pass


if __name__ == "__main__":
    cli()
```

It's documented here: https://typer.tiangolo.com/tutorial/commands/#explicit-application

There's a bit more info in the issue/discussion.

If there's something else you would like to consider, let's continue in the discussion. :nerd_face: 

For now, I'll pass on this one, but thanks for the effort! :cake:

**Pull request closed without merging**
